// Usage: pnpm faces:pack [--avatar avatar1] [--emote defeat]
//
// Writes, for every avatar and every clip it has packed (the idle plate plus
// each emote sheet), the two files a browser needs to put a real face on the
// avatar's blank face plate:
//
//   public/sprites/faces/<avatar>/<clip>.png   the plate mask, one alpha strip
//                                              laid out exactly like the sheet
//   public/sprites/faces/<avatar>/<clip>.json  one 2x3 affine per frame, in the
//                                              unit square of the squared photo
//
// and regenerates src/lib/domain/faces/faces.manifest.ts from what landed.
//
// The maths lives in scripts/face/fit.py (numpy + Pillow) -- see its README for
// why the segmentation has to run over a whole clip rather than frame by frame.
// Nothing here needs the network, and nothing here needs a photo: the matrices
// are normalised, so the same numbers come out whoever is in the picture.
import { execFileSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const ASSET_DIR = join(ROOT, "public/sprites/faces");
const MANIFEST_TS = join(ROOT, "src/lib/domain/faces/faces.manifest.ts");
const EMOTE_MANIFEST = join(ROOT, "public/sprites/emotes/manifest.json");

/** The idle plate is a still, not a strip, but it wears the same blank face. */
const PLATE = "plate";

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i += 2) {
    if (!argv[i].startsWith("--")) continue;
    out[argv[i].slice(2)] = argv[i + 1] ?? "";
  }
  return out;
}

const args = parseArgs(process.argv.slice(2));
const packed = JSON.parse(readFileSync(EMOTE_MANIFEST, "utf8"));
const avatars = args.avatar ? [args.avatar] : Object.keys(packed).sort();

mkdirSync(ASSET_DIR, { recursive: true });

for (const avatar of avatars) {
  const clips = args.emote
    ? [args.emote]
    : [PLATE, ...Object.keys(packed[avatar]).sort()];
  for (const clip of clips) {
    execFileSync(
      "python3",
      [
        "scripts/face/fit.py",
        "--avatar",
        avatar,
        "--emote",
        clip,
        "--assets",
        ASSET_DIR,
      ],
      { cwd: ROOT, stdio: "inherit" }
    );
  }
}

// ---- the manifest -----------------------------------------------------------
// Only what a screen needs to decide WITHOUT fetching: where the two files are,
// how many frames there are, and on how many of them the face is visible at all.
// `painted: 0` is a real answer -- walking away from camera shows no face, and a
// runtime that reads it skips the fetch and the composite entirely.
const manifest = {};
for (const avatar of Object.keys(packed).sort()) {
  const clips = [PLATE, ...Object.keys(packed[avatar]).sort()];
  const entries = {};
  for (const clip of clips) {
    const json = join(ASSET_DIR, avatar, `${clip}.json`);
    const mask = join(ASSET_DIR, avatar, `${clip}.png`);
    if (!(existsSync(json) && existsSync(mask))) continue;
    const body = JSON.parse(readFileSync(json, "utf8"));
    entries[clip] = {
      mask: `/sprites/faces/${avatar}/${clip}.png`,
      transforms: `/sprites/faces/${avatar}/${clip}.json`,
      frames: body.n,
      painted: body.f.filter(Boolean).length,
      bytes: statSync(mask).size + statSync(json).size,
    };
  }
  if (Object.keys(entries).length) manifest[avatar] = entries;
}

const body = Object.entries(manifest)
  .map(([avatar, clips]) => {
    const rows = Object.entries(clips)
      .map(
        ([clip, e]) =>
          `    ${/^[a-z][a-z0-9]*$/i.test(clip) ? clip : JSON.stringify(clip)}: {\n` +
          `      mask: ${JSON.stringify(e.mask)},\n` +
          `      transforms: ${JSON.stringify(e.transforms)},\n` +
          `      frames: ${e.frames},\n` +
          `      painted: ${e.painted},\n` +
          `      bytes: ${e.bytes},\n` +
          "    },"
      )
      .join("\n");
    return `  ${avatar}: {\n${rows}\n  },`;
  })
  .join("\n");

mkdirSync(join(ROOT, "src/lib/domain/faces"), { recursive: true });
writeFileSync(
  MANIFEST_TS,
  "// GENERATED by scripts/faces/pack.mjs from public/sprites/faces/.\n" +
    "// Do not edit by hand: run `pnpm faces:pack` and commit both together.\n" +
    'import type { FaceSheet } from "./faces";\n\n' +
    "export const FACE_MANIFEST: Readonly<\n" +
    "  Record<string, Readonly<Record<string, FaceSheet>>>\n" +
    `> = {\n${body}\n};\n`
);

const total = Object.values(manifest)
  .flatMap((c) => Object.values(c))
  .reduce((n, e) => n + e.bytes, 0);
console.log(
  `\nfaces:pack wrote ${Object.values(manifest).reduce((n, c) => n + Object.keys(c).length, 0)} clips, ` +
    `${(total / 1024).toFixed(0)} KB in total, and regenerated faces.manifest.ts`
);
